baseurl = "/"
languageCode = "en-us"
title = "Action for Children Messenger"

[params]
  description = "Multi-channel messenger system to help with communicating with vulnerable people."

[[menu.main]]
    name = "Messenger"
    url  = "/messenger"
[[menu.main]]
    name = "Support"
    url  = "/support"
